#define MAX_STRING_SIZE 64

struct Obj {
    char exchange[MAX_STRING_SIZE];
    char symbol[MAX_STRING_SIZE];
    char isin[MAX_STRING_SIZE];
    char scripcode[MAX_STRING_SIZE];
    char securityType[MAX_STRING_SIZE];
    char securityDesc[MAX_STRING_SIZE];
    char expiryDate[MAX_STRING_SIZE];
    char optType[MAX_STRING_SIZE];
    float strikePrice;
    float multiplier;
    float tickSize;
    uint32_t lotSize;
    float divider;
    char baseCurrency[MAX_STRING_SIZE];
    char settleCurrency[MAX_STRING_SIZE];
    uint32_t digits;
    float lowerBand;
    float upperBand;
    float prevClose;
    char productId[MAX_STRING_SIZE];
    float initialMargin;
    float tenderMargin;
    float totalMargin;
    float additionalLongMargin;
    float additionalShortMargin;
    float deliveryLongMargin;
    float deliveryShortMargin;
    float mwpl;
    bool suspend;
    bool algoRestricted;
    bool restrictedScript;
    bool bcastInclude;
    char productGroupName[MAX_STRING_SIZE];
    float haircut;
    char underlineSecurityId[MAX_STRING_SIZE];
    char underlineSymbol[MAX_STRING_SIZE];
    float yearlyHigh;
    float yearlyLow;
    char feedExchange[MAX_STRING_SIZE];
    char feedSecurityId[MAX_STRING_SIZE];
    uint32_t recNo;
    uint32_t maxSingleTransQty;
    char segment[MAX_STRING_SIZE];
    uint32_t token;
};
